version: '3'
services:
  mysql-m:
    image: mysql:latest
    restart: always
    volumes:
      - ./configs/master.cnf:/etc/mysql/my.cnf
      - ./data/data-master:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306

  mysql-s1:
    image: mysql:latest
    restart: always
    volumes:
      - ./configs/s1.cnf:/etc/mysql/my.cnf
      - ./data/data-slave1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    depends_on:
      - mysql-m
    ports:
      - 3307:3306

  mysql-s2:
    image: mysql:latest
    restart: always
    volumes:
      - ./configs/s2.cnf:/etc/mysql/my.cnf
      - ./data/data-slave2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    depends_on:
      - mysql-m
    ports:
      - 3308:3306